name: Promazat epizody ve 21:58

on:
  schedule:
    # 19:58 UTC = 21:58 českého letního času (SELČ / CEST)
    # V zimním čase (CET) by bylo potřeba upravit na '58 20 * * *'
    - cron: '58 19 * * *'
  workflow_dispatch: # Umožní ruční spuštění přes záložku Actions pro otestování

jobs:
  clear-episodes-file:
    runs-on: ubuntu-latest
    steps:
      - name: Načíst repozitář
        uses: actions/checkout@v4

      - name: Vyprázdnit episodes.json
        run: |
          echo "{}" > episodes.json

      - name: Uložit změny (Commit & Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Auto-clear episodes.json (21:58)" || exit 0
          git push
